### ISSUE TITLE
Error: Repeat unicode, glyph index: 1

### ISSUE THREAD

**Issue by freekoy** [ecomfe/fontmin#70]
在字蛛下使用 fontmin报错了？
汉仪字体
```
Error: Repeat unicode, glyph index: 1
    at Object.error.raise (C:\Users\Administrator\AppData\Roaming\npm\node_modules\font-spider\node_modules\fonteditor-core\ttf\error.js:28:13)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\font-spider\node_modules\fonteditor-core\ttf\ttfwriter.js:93:27
    at Array.forEach (<anonymous>)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\font-spider\node_modules\fonteditor-core\ttf\ttfwriter.js:91:26
    at Array.forEach (<anonymous>)
    at TTFWriter.resolve (C:\Users\Administrator\AppData\Roaming\npm\node_modules\font-spider\node_modules\fonteditor-core\ttf\ttfwriter.js:87:14)
    at TTFWriter.write (C:\Users\Administrator\AppData\Roaming\npm\node_modules\font-spider\node_modules\fonteditor-core\ttf\ttfwriter.js:217:13)
    at minifyTtf (C:\Users\Administrator\AppData\Roaming\npm\node_modules\font-spider\node_modules\fontmin\plugins\glyph.js:97:29)
    at Through2._transform (C:\Users\Administrator\AppData\Roaming\npm\node_modules\font-spider\node_modules\fontmin\plugins\glyph.js:153:27)
    at Through2.Transform._read (C:\Users\Administrator\AppData\Roaming\npm\node_modules\font-spider\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:159:10)
```

**Comment by JsBeta** [comment]
楼主 我也同样报这个错误，最后替换另外一种字体文件就不再报错了。不知楼主怎么解决的
